Q1='''SELECT COUNT(id) FROM Movie where year < 2000;'''
Q2='''SELECT AVG(rank) FROM Movie where year = 1991;'''
Q3='''SELECT MIN(rank) FROM Movie where year = 1991;'''
Q4='''SELECT fname,lname FROM Actor INNER JOIN Cast on id = pid WHERE mid=27;'''
Q5='''SELECT COUNT(mid) FROM Cast INNER JOIN Actor on id = pid WHERE fname = 'Jon' and lname = 'Dough';'''
Q6='''SELECT name FROM Movie WHERE year BETWEEN 2003 and 2006 and name like  'Young Latin Girls%';'''
Q7='''SELECT fname,lname FROM(Director INNER JOIN MovieDirector on Director.id=MovieDirector.did)INNER JOIN Movie on Movie.id=MovieDirector.mid WHERE name LIKE 'Star Trek%';'''
Q8='''SELECT name FROM (Movie INNER JOIN Cast on `Movie`.id=`Cast`.mid)INNER JOIN MovieDirector on `MovieDirector`.mid=`Movie`.id INNER JOIN Director on `MovieDirector`.did=`Director`.id INNER JOIN Actor on `Cast`.pid=`Actor`.id WHERE (`Actor`.fname='Jackie (I)' and `Actor`.lname='Chan') and (`Director`.fname='Jackie (I)' and `Director`.lname='Chan') ORDER BY name ASC;'''
Q9='''SELECT fname,lname FROM (Director INNER JOIN MovieDirector on MovieDirector.did = Director.id) INNER JOIN Movie on MovieDirector.mid = Movie.id  WHERE year = 2001  GROUP BY `Director`.id HAVING COUNT(Movie.id) >= 4 ORDER BY fname ASC;'''
Q10='''SELECT gender,COUNT(id) FROM Actor GROUP BY gender ORDER BY gender ASC;'''
Q11='''SELECT `m1`.name,`m2`.name,`m1`.rank,`m1`.year FROM  Movie as m1 CROSS JOIN Movie as m2 where (`m1`.year = `m2`.year) and (`m1`.rank = `m2`.rank) and (`m1`.name <> `m2`.name) ORDER BY `m1`.name ASC LIMIT 100;'''
Q12='''SELECT fname,year,AVG(rank) FROM Actor INNER JOIN Cast on Actor.id=pid INNER JOIN Movie on Movie.id=mid GROUP BY Actor.id,year ORDER BY fname ASC,year DESC LIMIT 100;'''
Q13='''SELECT Actor.fname,Director.fname,AVG(rank) as score FROM (Actor INNER JOIN Cast on `Cast`.pid = `Actor`.id) INNER JOIN Movie on `Movie`.id = `Cast`.mid INNER JOIN MovieDirector on MovieDirector.mid = `Movie`.id INNER JOIN Director on `Director`.id = `MovieDirector`.did GROUP BY `Director`.id , `Actor`.id HAVING COUNT(Movie.id) >= 5 ORDER BY score DESC,`Director`.fname ASC,`Actor`.fname DESC LIMIT 100;'''
